apiVersion : apps/v1
kind: Deployment
metadata:
  name: springpetclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springpetclinic
  template:
    metadata:
      labels:
        app: springpetclinic
    spec:
      containers:
        - name: springpetclinic
          image: ghcr.io/canarysplayground/springpetclinic:${{github.run_number}}
          ports:
          - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
    name: springpetclinic
spec:
    type: LoadBalancer
    ports:
    - port: 8085
      targetPort: 8085
    selector:
        app: springpetclinic
