name: CI

on:

  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
#       - name: Build Project
#         run: mvn clean package 
      
#       - name: Docker Setup QEMU
#         uses: docker/setup-qemu-action@v1.0.1
        
#       - name: Docker Setup Buildx
#         uses: docker/setup-buildx-action@v1.0.3
  
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CAT_PA }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/pimebank-com-bd/maniktest:latest
            ghcr.io/pimebank-com-bd/aniktest{github.run_number}}
    
           
        
