name: Spring-Petclinic.Docker

on:
  push:
    branches: [ main ] 
  workflow_dispatch:
  
jobs:
  dockerpush:
    name: DOCKER BUILD & PUSH
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: springdemoregistry.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            canarysplayground/sringpetclinic:latest
            canarysplayground/sringpetclinic:${{github.run_number}}
      
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
