name: Spring-Petclinic.Docker

on:
  push:
    branches: [ main ] 
  workflow_dispatch:
  
jobs:
  dockerpush:
    name: DOCKER BUILD & PUSH
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
     
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{ secrets.CR_PAT }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/sringpetclinic:latest
            ghcr.io/canarysplayground/sringpetclinic:${{github.run_number}}
         
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  AKS_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: dockerpush
    steps:
    - name: Checkout
      uses: actions/checkout@v2   
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: tailspin-k8s
        cluster-name: springpetclinic
    
    - uses: azure/k8s-create-secret@v1
      name: Create imagepullsecret for ACR
      with:
        container-registry-url: ghcr.io
        container-registry-username: ${{ github.repository_owner }}
        container-registry-password: ${{ secrets.CR_PAT }}
        secret-name: canarysplayground-registry-connection
        
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:       
        manifests: deployment.yml      
        images: ghcr.io/canarysplayground/springpetclinic:latest
        imagepullsecrets: |
          canarysplayground-registry-connection
        force: true
